# A basic docker file to install Jenkins War file
FROM jenkinsci/jenkins:2.0-beta-1
MAINTAINER Navatha Raagi

USER root
USER Jenkins
url=http://mirrors.jenkins.io/war-stable/latest/jenkins.war dest=/opt/apache-tomcat-8.5.23/webapps/jenkins.war
